# Generated by Django 5.2 on 2025-11-19 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_unidadproducto_pedido_item'),
        ('usuarios', '0019_devolucion_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='unidad_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.unidadproducto'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='usuarios.pedido'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='seleccionada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='unidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion_completa',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='nombre_completo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='notas_entrega',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='usuarios.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
