# Generated by Django 5.2 on 2025-11-19 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_imgproduc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('devuelto', 'Devuelto')], default='disponible', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='productos.producto')),
            ],
        ),
    ]
