# Generated by Django 5.2 on 2025-11-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_unidadproducto'),
        ('usuarios', '0019_devolucion_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadproducto',
            name='pedido_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='usuarios.pedidoitem'),
        ),
    ]
